[package]
name = "time-tracker"
version = "0.1.2"
authors = ["ztulloch <ztulloch@gmail.com>", "maikwoehl <maik.woehl@outlook.de>"]

[dependencies]
getopts = "0.2"
csv = "1.0.0"
serde_derive = "1.0"
serde = "1.0"
chrono = "0.4.4"

[dev-dependencies]
assert_cli = "^0.5"

